/**
 * RootLayout Component
 * ---
 * This file defines the root layout for the entire Next.js application.
 * It applies global settings such as metadata, fonts, and background styling.
 *
 * Features:
 * - Configures global fonts (Playfair Display, Lato, Cinzel) using `next/font/google`
 * - Applies a gradient background and a decorative image
 * - Provides consistent layout for all pages
 */

import type { Metadata } from "next";
import { Playfair_Display, Lato, Cinzel } from "next/font/google";
import Image from "next/image";
import "./globals.css";

/**
 * Playfair Display — Elegant serif for headings.
 */
const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

/**
 * Lato — Clean sans-serif for paragraph text.
 */
const lato = Lato({
  variable: "--font-lato",
  weight: "400",
  subsets: ["latin"],
});

/**
 * Cinzel — Classic serif for accent or title use.
 */
const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Inspire Flow",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
    apple: "/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${playfair.variable} ${lato.variable} ${cinzel.variable}`}
    >
      <body className="min-h-screen bg-linear-to-br from-white via-pink-300 to-yellow-300 flex flex-col items-center justify-center animate-gradient">
        <Image
          src="/quote-bg.png"
          alt="Quotation mark background"
          width={400}
          height={400}
          priority
          className="
            absolute
            top-0 left-0
            translate-x-1/5 translate-y-1/4
            opacity-100
            w-0 sm:w-[400px] md:w-[450px]
            pointer-events-none select-none
            z-0
          "
        />
        {children}
      </body>
    </html>
  );
}
